AllCops:
  TargetRubyVersion: 2.3

Style/MethodCallParentheses:
  Enabled: false

Style/TrailingCommaInArguments:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Metrics/LineLength:
  Max: 100

Metrics/AbcSize:
  Max: 20

Metrics/MethodLength:
  Max: 20

Style/Documentation:
  Enabled: false

Style/TrailingCommaInLiteral:
  EnforcedStyleForMultiline: constistent_comma

Style/ClassAndModuleChildren:
  Enabled: false

Style/AlignParameters:
  Enabled: false

Style/DotPosition:
  Enabled: false

Style/MultilineMethodCallIndentation:
  Enabled: false

Metrics/ClassLength:
  Max: 150

Metrics/BlockLength:
  Exclude:
    - '**/*_spec.rb'
    - 'spec/**/*'
